### ISSUE TITLE
Question on controling the robot arm

### ISSUE THREAD

**Issue by johnnevins** [Shaka-Labs/ACT#2]
Hi, thanks much for sharing this!
I've read through the readme, it seems that you use a local PC with GPU to implement the inference of imitation learning. Since currently I don't have a PC with discrete GPU, wonder would it be possible to use a remote GPU server to control the arm and how? 

Appreciated your help:)

**Comment by vateseif** [comment]
actually i do inference on the CPU of an M3 macbook pro so it should be fine. remote GPU would add quite some latency
