### ISSUE TITLE
Can this project train the two arms operation.

### ISSUE THREAD

**Issue by starjokers** [Shaka-Labs/ACT#3]
Hi, 

We record more than 50 times to pick up things, but after training, when we evaluate it, the arm moved, but it can not locate the thing which should be picked up. We found that one servo direction is reversed in either leader or the follower when we gather them. Will it cause the locating wrong?

 Additionally, if we want to train the operation of folding cloths with two arms, will it work? Can we modify the code little to implement the targets？
Thank you!

**Comment by vateseif** [comment]
it is likely that the model won't work if the robot and camera move with respect to each other compared to your training data.  

there is a proper way to assemble and mount all the motors so you shouldn't have any reversed servo. if you don't feel like reassembling the robot you should change the code (i.e. put a negative sign to the servo position reading). as long as you do inference in the same setting in which your training data was collected it should work fine.

this repo would only work for this low-cost robot (i.e. 5 servo motors) if you don't change the code. i suggest you checkout Lerobot from huggingface https://github.com/huggingface/lerobot
